import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

class Member {
  name: string;
  surname: string;
  birthday: Date;
  gender: boolean;
  age: number;

  constructor() {
    console.log("ctor çalıştı")

    this.name = "Name";
    this.surname = "Surname";
    this.birthday = new Date();
    this.gender = true;
    this.age = 99;

  }
}

export default function Home() {

  const User = {
    firstName: "Angela",
    lastName: "Davis",
    role: "Professor",
  }

  type Features = {
    age: Number;
    city: String;

  }


  console.log(User.firstName)

  function sendMessage(id: number, name: string, features: Features) {
    console.log(`${id} numaralı ${name} özellikleri ${features.age} ${features.city}`);
  }

  function getMember(): string {
    const member = new Member();
    member.name = "Düzgün Emre";
    member.surname = "Özkan";
    member.birthday = new Date();
    member.gender = true;
    member.age = 35;

    return member.name;
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Merhaba <a href='https://nextjs.org'>Next.js!</a>
        </h1>
        {sendMessage(1, "Emre", { age: 32, city: "İstanbul" })}
        {console.log(getMember())}
      </main>
    </div>
  );
}
